name: Go (lint + test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: checkout
        uses: actions/checkout@v2
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: lint
        uses: golangci/golangci-lint-action@v3
	with: 
	  version: v1.46
	  only-new-issues: true	
      - name: test
        run: make test
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: build/test-results/cover.out
